apiVersion: v1
kind: Service
metadata:
  name: {{ include "compliance.fullname" . }}-api
  labels:
    {{- include "compliance.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    {{- include "compliance.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: http
