apiVersion: v1
kind: Service
metadata:
  name: {{ include "compliance.fullname" . }}-qdrant
  labels:
    {{- include "compliance.labels" . | nindent 4 }}
    app.kubernetes.io/component: qdrant
spec:
  clusterIP: None
  selector:
    {{- include "compliance.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: qdrant
  ports:
    - name: http
      port: 6333
      targetPort: http
    - name: grpc
      port: 6334
      targetPort: grpc
