apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "compliance.apiServiceAccount" . }}
  labels:
    {{- include "compliance.labels" . | nindent 4 }}
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "compliance.webServiceAccount" . }}
  labels:
    {{- include "compliance.labels" . | nindent 4 }}
  {{- with .Values.web.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
