/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/screen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Screen */
        post: operations["screen_screen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Answer */
        Answer: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Synthesised */
            synthesised: boolean;
            /** Text */
            text: string;
        };
        /** Citation */
        Citation: {
            /** Clause Id */
            clause_id: string;
            /** Clause Path */
            clause_path: string;
            /** Effective From */
            effective_from?: string | null;
            /** Effective To */
            effective_to?: string | null;
            /** Quote */
            quote: string;
            /** Support */
            support: number;
        };
        /** ComplianceAssessment */
        ComplianceAssessment: {
            /** Applicable Regulations */
            applicable_regulations: string[];
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Model Version */
            model_version: string;
            /** Prompt Version */
            prompt_version: string;
            /** Required Actions */
            required_actions: string[];
            risk_rating: components["schemas"]["RiskRating"];
            /** Txn Id */
            txn_id: string;
            /** Unresolved Questions */
            unresolved_questions: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** QueryRequest */
        QueryRequest: {
            /** As Of */
            as_of?: string | null;
            /** Jurisdictions */
            jurisdictions?: ("IN" | "EU" | "US" | "GLOBAL")[] | null;
            /** Question */
            question: string;
        };
        /**
         * RiskRating
         * @enum {string}
         */
        RiskRating: "low" | "medium" | "high" | "blocked";
        /** TransactionPayload */
        TransactionPayload: {
            /** Amount */
            amount?: number | string | null;
            /** Appropriateness Assessed */
            appropriateness_assessed?: boolean | null;
            /** Counterparty Type */
            counterparty_type?: string | null;
            /** Currency */
            currency?: string | null;
            /** High Risk Jurisdiction */
            high_risk_jurisdiction?: boolean | null;
            /** Instrument */
            instrument?: string | null;
            /** Jurisdictions */
            jurisdictions?: ("IN" | "EU" | "US" | "GLOBAL")[] | null;
            /** Kyc Status */
            kyc_status?: boolean | null;
            /** Large Exposure Threshold Exceeded */
            large_exposure_threshold_exceeded?: boolean | null;
            /** Priority Sector Reporting Required */
            priority_sector_reporting_required?: boolean | null;
            /** Txn Id */
            txn_id: string;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    query_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Answer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screen_screen_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceAssessment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
